language: node_js
node_js:
  - '6'
  - '8'
  - node
cache:
  directories:
    - node_modules
before_script:
  - npm install -g typescript
script:
  - npm run build
  - npm test
after_success: npm run coverage
